--- a/.github/workflows/crossbuild-mingw.yml
+++ b/.github/workflows/crossbuild-mingw.yml
@@ -78,4 +78,4 @@
           fi
       - name: Populate release
         run: |
-          gh release upload ${{ github.ref_name }} harfbuzz-win*-${{ github.ref_name }}.zip --clobber
+          gh release upload ${{ github.ref_name }} harfbuzz-win*-${{ github.ref_name }}.zip --clobber